In [1]:
import numpy as np
import pandas as pd

In [3]:
pd.isnull(np.array([1,np.nan,2,3]))

array([False,  True, False, False])

In [4]:
pd.isna(np.array([1,2,np.nan]))

array([False, False,  True])

In [6]:
pd.notnull(2)

True

In [7]:
pd.notna(2)

True

In [8]:
pd.isnull(pd.Series([1,2,np.nan]))

0    False
1    False
2     True
dtype: bool

In [12]:
pd.isnull(pd.DataFrame({
            'column1' : np.array([1,np.nan,2]),
            'column2' : np.array([np.nan,7,np.nan]),
            'column3' : np.array([1,np.nan,4])
        }))

column1  column2  column3
0    False     True    False
1     True    False     True
2    False     True    False

In [27]:
pd.Series([1, 2, np.nan]).count()

2

In [28]:
pd.Series([1, 2, np.nan]).sum()

3.0

In [31]:
pd.Series([2, 1, np.nan]).mean()

1.5

In [14]:
s=pd.Series([1,2,np.nan,3])

In [20]:
pd.notna(s)

0     True
1     True
2    False
3     True
dtype: bool

In [24]:
np.isfinite(s).sum()

3

In [25]:
pd.notna(s).sum()

3

In [26]:
pd.isna(s).sum()

1

In [36]:
pd.notna(s)

0     True
1     True
2    False
3     True
dtype: bool

In [37]:
s.notna()

0     True
1     True
2    False
3     True
dtype: bool

In [38]:
s[pd.notna(s)]

0    1.0
1    2.0
3    3.0
dtype: float64

In [39]:
s[s.notna()]

0    1.0
1    2.0
3    3.0
dtype: float64

In [40]:
s

0    1.0
1    2.0
2    NaN
3    3.0
dtype: float64

In [41]:
s.dropna()

0    1.0
1    2.0
3    3.0
dtype: float64

In [42]:
s.dropna().sum()

6.0

In [43]:
s.sum()

6.0

In [45]:
df=pd.DataFrame({
        'Col A':[1,2,np.nan,4],
        'Col B':[5,6,7,np.nan],
        'Col C':[np.nan,8,9,10],
        'Col D':[11,12,13,14]
    })

In [46]:
df

Col A  Col B  Col C  Col D
0    1.0    5.0    NaN     11
1    2.0    6.0    8.0     12
2    NaN    7.0    9.0     13
3    4.0    NaN   10.0     14

In [48]:
df.shape

(4, 4)

In [50]:
df.describe()

Col A  Col B  Col C      Col D
count  3.000000    3.0    3.0   4.000000
mean   2.333333    6.0    9.0  12.500000
std    1.527525    1.0    1.0   1.290994
min    1.000000    5.0    8.0  11.000000
25%    1.500000    5.5    8.5  11.750000
50%    2.000000    6.0    9.0  12.500000
75%    3.000000    6.5    9.5  13.250000
max    4.000000    7.0   10.0  14.000000

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Col A   3 non-null      float64
 1   Col B   3 non-null      float64
 2   Col C   3 non-null      float64
 3   Col D   4 non-null      int64  
dtypes: float64(3), int64(1)
memory usage: 256.0 bytes


In [53]:
df.isna()

Col A  Col B  Col C  Col D
0  False  False   True  False
1  False  False  False  False
2   True  False  False  False
3  False   True  False  False

In [55]:
df.isnull().sum()

Col A    1
Col B    1
Col C    1
Col D    0
dtype: int64

In [56]:
df.dropna()

Col A  Col B  Col C  Col D
1    2.0    6.0    8.0     12

In [57]:
df.dropna(axis=1)

Col D
0     11
1     12
2     13
3     14

In [60]:
df.dropna(axis='columns')

Col D
0     11
1     12
2     13
3     14

In [63]:
df.dropna()

Col A  Col B  Col C  Col D
1    2.0    6.0    8.0     12

In [64]:
df.dropna(how='all')

Col A  Col B  Col C  Col D
0    1.0    5.0    NaN     11
1    2.0    6.0    8.0     12
2    NaN    7.0    9.0     13
3    4.0    NaN   10.0     14

In [65]:
df.dropna(how='any')

Col A  Col B  Col C  Col D
1    2.0    6.0    8.0     12

In [113]:
df2 = pd.DataFrame({
    'Column A': [1, np.nan, 30],
    'Column B': [2, np.nan, 31],
    'Column C': [np.nan, np.nan, 100]
})

In [114]:
df2

Column A  Column B  Column C
0       1.0       2.0       NaN
1       NaN       NaN       NaN
2      30.0      31.0     100.0

In [115]:
df2.dropna(how='any')

Column A  Column B  Column C
2      30.0      31.0     100.0

In [116]:
df2.dropna(how='all')

Column A  Column B  Column C
0       1.0       2.0       NaN
2      30.0      31.0     100.0

You can also use the thresh parameter to indicate a threshold (a minimum number) of non-null values for the row/column to be kept:

In [118]:
df3 = pd.DataFrame({
    'Column A': [1, np.nan, 30,np.nan],
    'Column B': [2, np.nan, 31,88],
    'Column C': [np.nan, np.nan, 100,np.nan],
    'Column D': [2, 3, 31,88],
    'Column E': [np.nan, np.nan,np.nan,np.nan]
})

In [119]:
df3

Column A  Column B  Column C  Column D  Column E
0       1.0       2.0       NaN         2       NaN
1       NaN       NaN       NaN         3       NaN
2      30.0      31.0     100.0        31       NaN
3       NaN      88.0       NaN        88       NaN

In [122]:
df3.dropna(thresh=3)

Column A  Column B  Column C  Column D  Column E
0       1.0       2.0       NaN         2       NaN
2      30.0      31.0     100.0        31       NaN

In [124]:
df3

Column A  Column B  Column C  Column D  Column E
0       1.0       2.0       NaN         2       NaN
1       NaN       NaN       NaN         3       NaN
2      30.0      31.0     100.0        31       NaN
3       NaN      88.0       NaN        88       NaN

In [123]:
df3.dropna(thresh=0,axis=1)

Column A  Column B  Column C  Column D  Column E
0       1.0       2.0       NaN         2       NaN
1       NaN       NaN       NaN         3       NaN
2      30.0      31.0     100.0        31       NaN
3       NaN      88.0       NaN        88       NaN

In [125]:
df3.dropna(thresh=1,axis=1)

Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         2
1       NaN       NaN       NaN         3
2      30.0      31.0     100.0        31
3       NaN      88.0       NaN        88

In [126]:
df3.dropna(thresh=2,axis=1)

Column A  Column B  Column D
0       1.0       2.0         2
1       NaN       NaN         3
2      30.0      31.0        31
3       NaN      88.0        88

In [128]:
df3.dropna(thresh=3,axis=1)

Column B  Column D
0       2.0         2
1       NaN         3
2      31.0        31
3      88.0        88

In [129]:
df3.dropna(thresh=4,axis=1)

Column D
0         2
1         3
2        31
3        88

In [130]:
df3.dropna(thresh=5,axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

<B>FINDING NULL VALUES</B>

In [132]:
s

0    1.0
1    2.0
2    NaN
3    3.0
dtype: float64

Filling nan with an arbitary value(here, 0 or mean value)

In [136]:
s.fillna(0)

0    1.0
1    2.0
2    0.0
3    3.0
dtype: float64

In [137]:
s.mean()

2.0

In [138]:
s.fillna(s.mean())

0    1.0
1    2.0
2    2.0
3    3.0
dtype: float64

<b>Filling nulls with contiguous (close) values</b>

The method argument is used to fill null values with other values close to that null one:

In [141]:
s

0    1.0
1    2.0
2    NaN
3    3.0
dtype: float64

In [139]:
s.fillna(method='ffill')

0    1.0
1    2.0
2    2.0
3    3.0
dtype: float64

In [140]:
s.fillna(method='bfill')

0    1.0
1    2.0
2    3.0
3    3.0
dtype: float64

In [142]:
pd.Series([np.nan, 3, np.nan, 9]).fillna(method='ffill')

0    NaN
1    3.0
2    3.0
3    9.0
dtype: float64

In [143]:
pd.Series([1, np.nan, 3, np.nan, np.nan]).fillna(method='bfill')

0    1.0
1    3.0
2    3.0
3    NaN
4    NaN
dtype: float64

In [146]:
df3

Column A  Column B  Column C  Column D  Column E
0       1.0       2.0       NaN         2       NaN
1       NaN       NaN       NaN         3       NaN
2      30.0      31.0     100.0        31       NaN
3       NaN      88.0       NaN        88       NaN

In [154]:
df3.fillna({'Column A':15,'Column B':df3['Column B'].mean(),'Column C':10,'Column E':0})

Column A   Column B  Column C  Column D  Column E
0       1.0   2.000000      10.0         2       0.0
1      15.0  40.333333      10.0         3       0.0
2      30.0  31.000000     100.0        31       0.0
3      15.0  88.000000      10.0        88       0.0

In [155]:
df

Col A  Col B  Col C  Col D
0    1.0    5.0    NaN     11
1    2.0    6.0    8.0     12
2    NaN    7.0    9.0     13
3    4.0    NaN   10.0     14

In [156]:
df.fillna(method='bfill')

Col A  Col B  Col C  Col D
0    1.0    5.0    8.0     11
1    2.0    6.0    8.0     12
2    4.0    7.0    9.0     13
3    4.0    NaN   10.0     14

In [157]:
df.fillna(method='bfill',axis=1)

Col A  Col B  Col C  Col D
0    1.0    5.0   11.0   11.0
1    2.0    6.0    8.0   12.0
2    7.0    7.0    9.0   13.0
3    4.0   10.0   10.0   14.0

In [158]:
df.fillna(method='ffill')

Col A  Col B  Col C  Col D
0    1.0    5.0    NaN     11
1    2.0    6.0    8.0     12
2    2.0    7.0    9.0     13
3    4.0    7.0   10.0     14

In [159]:
df.fillna(method='ffill',axis=1)

Col A  Col B  Col C  Col D
0    1.0    5.0    5.0   11.0
1    2.0    6.0    8.0   12.0
2    NaN    7.0    9.0   13.0
3    4.0    4.0   10.0   14.0

In [162]:
s

0    1.0
1    2.0
2    NaN
3    3.0
dtype: float64

In [160]:
s.count()

3

In [161]:
s.dropna().count()

3

In [163]:
len(s)

4

In [165]:
missingValue=len(s)!=len(s.dropna())

In [166]:
missingValue

True

In [167]:
s.isnull().values

array([False, False,  True, False])

In [168]:
s.isnull().values.any()

True

In [169]:
s.isnull().values.all()

False